/* Generated by Cython 3.0.11 */

#ifndef __PYX_HAVE__libpythonWrapper
#define __PYX_HAVE__libpythonWrapper

#include "Python.h"

#ifndef __PYX_HAVE_API__libpythonWrapper

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *avframe_to_rgb(struct AVFrame *, int, int);
__PYX_EXTERN_C void streamStarted(char const *);
__PYX_EXTERN_C void streamFinished(char const *);
__PYX_EXTERN_C void onVideoFrame(char const *, struct AVFrame *);
__PYX_EXTERN_C void onAudioFrame(char const *, PyObject *);
__PYX_EXTERN_C void onVideoPacket(char const *, struct AVPacket *);
__PYX_EXTERN_C void onAudioPacket(char const *, struct AVPacket *);
__PYX_EXTERN_C void setVideoStreamInfo(char const *, void const *);
__PYX_EXTERN_C void setAudioStreamInfo(char const *, void const *);

#endif /* !__PYX_HAVE_API__libpythonWrapper */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initlibpythonWrapper(void);
#else
/* WARNING: Use PyImport_AppendInittab("libpythonWrapper", PyInit_libpythonWrapper) instead of calling PyInit_libpythonWrapper directly from Python 3.5 */
PyMODINIT_FUNC PyInit_libpythonWrapper(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"libpythonWrapper\", PyInit_libpythonWrapper) instead of calling PyInit_libpythonWrapper directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"libpythonWrapper\", PyInit_libpythonWrapper) instead of calling PyInit_libpythonWrapper directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"libpythonWrapper\", PyInit_libpythonWrapper) instead of calling PyInit_libpythonWrapper directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_libpythonWrapper_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_libpythonWrapper() __PYX_WARN_IF_PyInit_libpythonWrapper_INIT_CALLED(PyInit_libpythonWrapper())
#endif
#endif

#endif /* !__PYX_HAVE__libpythonWrapper */
